CD\ C:\Users\Josh\Documents\GitHub\Iron-Age-Terrarum-Antiqua\Iron Age Terrarum Antiqua\decisions\vfs

copy Imperial.txt egyptian_pagan.txt
copy Imperial.txt atenist.txt
copy Imperial.txt berber_main.txt
copy Imperial.txt berber_pagan_reformed.txt
copy Imperial.txt illyrian_main.txt
copy Imperial.txt thracian_main.txt
copy Imperial.txt zalmoxism.txt
copy Imperial.txt zalmoxism_reformed.txt
copy Imperial.txt norse_pagan_reformed.txt
copy Imperial.txt norse_pagan.txt
copy Imperial.txt east_germanic_pagan_reformed.txt
copy Imperial.txt east_germanic_pagan.txt
copy Imperial.txt germanic_pagan_reformed.txt
copy Imperial.txt germanic_pagan.txt
copy Imperial.txt celtic_pagan.txt
copy Imperial.txt celtic_pagan_reformed.txt
copy Imperial.txt punic_main.txt
copy Imperial.txt canaanite_pagan.txt
copy Imperial.txt canaanite_pagan_reformed.txt
copy Imperial.txt ossetian_pagan_reformed.txt
copy Imperial.txt ossetian_pagan.txt
copy Imperial.txt iranian_pagan.txt
copy Imperial.txt iranian_pagan_reformed.txt
copy Imperial.txt zoroastrian.txt
copy Imperial.txt zurvanite.txt
copy Imperial.txt sogdian_zoroastrian.txt
copy Imperial.txt bihafaridism.txt
copy Imperial.txt hanifiyya.txt
copy Imperial.txt chinese_pagan_reformed.txt
copy Imperial.txt chinese_pagan.txt
copy Imperial.txt tibetan_pagan_reformed.txt
copy Imperial.txt tibetan_pagan.txt
copy Imperial.txt sanamahi_reformed.txt
copy Imperial.txt sanamahi.txt
copy Imperial.txt dravidian_pagan_reformed.txt
copy Imperial.txt armenian_pagan.txt
copy Imperial.txt armenian_pagan_reformed.txt
copy Imperial.txt yazidi.txt
copy Imperial.txt jewish.txt
copy Imperial.txt samaritan.txt
copy Imperial.txt grand_sanhedrin.txt
copy Imperial.txt temple_judaism.txt
copy Imperial.txt karaite.txt
copy Imperial.txt hindu.txt
copy Imperial.txt jain.txt
copy Imperial.txt buddhist.txt
copy Imperial.txt vajrayana_buddhist.txt
copy Imperial.txt mahayana_buddhist.txt
copy Imperial.txt georgian_pagan.txt
copy Imperial.txt georgian_pagan_reformed.txt
copy Imperial.txt anatolian_main.txt
copy Imperial.txt phrygian_main.txt
copy Imperial.txt hittite_main.txt
copy Imperial.txt marduk_cult.txt
copy Imperial.txt elamite_pagan_reformed.txt
copy Imperial.txt elamite_pagan.txt
copy Imperial.txt arabic_main.txt
copy Imperial.txt south_semitic_pagan_reformed.txt
copy Imperial.txt south_semitic_pagan.txt
copy Imperial.txt hellenic_pagan_reformed.txt
copy Imperial.txt hellenic_pagan.txt
copy Imperial.txt alexandrian_pagan.txt
copy Imperial.txt roman_main.txt
copy Imperial.txt italic_main.txt
copy Imperial.txt pontic_main.txt
copy Imperial.txt etruscan_main.txt
copy Imperial.txt dravidian_main.txt
copy Imperial.txt lusitanian_main.txt
copy Imperial.txt iberian_main.txt
copy Imperial.txt aquitanian_main.txt
copy Imperial.txt marcionism.txt
copy Imperial.txt priscillianism.txt
copy Imperial.txt valentinianism.txt
copy Imperial.txt manichean.txt
copy Imperial.txt mandean.txt
copy Imperial.txt bogomilist.txt
copy Imperial.txt paulician.txt
copy Imperial.txt cathar.txt
copy Imperial.txt encratites.txt
copy Imperial.txt amidist.txt
copy Imperial.txt confucian.txt
copy Imperial.txt neoconfucian.txt
copy Imperial.txt taoist.txt
copy Imperial.txt neotaoist.txt
copy Imperial.txt hindukush.txt
copy Imperial.txt hindukush_reformed.txt
copy Imperial.txt zun_pagan.txt
copy Imperial.txt zun_pagan_reformed.txt
copy Imperial.txt bosporan_faith.txt
copy Imperial.txt arian.txt
copy Imperial.txt donatism.txt
copy Imperial.txt melitianism.txt
copy Imperial.txt novatianism.txt
copy Imperial.txt adoptionism.txt
copy Imperial.txt sabellianism.txt
copy Imperial.txt pelagianism.txt
copy Imperial.txt macedonianism.txt
copy Imperial.txt catholic.txt
copy Imperial.txt montanism.txt
copy Imperial.txt fraticelli.txt
copy Imperial.txt waldensian.txt
copy Imperial.txt lollard.txt
copy Imperial.txt orthodox.txt
copy Imperial.txt miaphysite.txt
copy Imperial.txt tondrakian.txt
copy Imperial.txt monophysite.txt
copy Imperial.txt monothelite.txt
copy Imperial.txt iconoclast.txt
copy Imperial.txt nestorian.txt
copy Imperial.txt eutychian.txt
copy Imperial.txt messalian.txt
copy Imperial.txt sunni.txt
copy Imperial.txt zikri.txt
copy Imperial.txt ibadi.txt
copy Imperial.txt kharijite.txt
copy Imperial.txt shiite.txt
copy Imperial.txt druze.txt
copy Imperial.txt qarmatian.txt
copy Imperial.txt hurufi.txt
copy Imperial.txt pagan.txt
copy Imperial.txt mesopotamian_paganism.txt
copy Imperial.txt mesopotamian_paganism_reformed.txt
copy Imperial.txt tengri_pagan_reformed.txt
copy Imperial.txt tengri_pagan.txt
copy Imperial.txt baltic_pagan_reformed.txt
copy Imperial.txt baltic_pagan.txt
copy Imperial.txt finnish_pagan_reformed.txt
copy Imperial.txt finnish_pagan.txt
copy Imperial.txt aztec_reformed.txt
copy Imperial.txt aztec.txt
copy Imperial.txt slavic_pagan_reformed.txt
copy Imperial.txt slavic_pagan.txt
copy Imperial.txt west_african_pagan_reformed.txt
copy Imperial.txt west_african_pagan.txt
copy Imperial.txt serer.txt
copy Imperial.txt bori.txt
copy Imperial.txt sol_invictus.txt
copy Imperial.txt egyptian_pagan_reformed.txt
copy Imperial.txt basque_pagan_reformed.txt
copy Imperial.txt basque_pagan.txt
copy Imperial.txt semitic_pagan_reformed.txt
copy Imperial.txt semitic_pagan.txt
copy Imperial.txt east_african_pagan_reformed.txt
copy Imperial.txt east_african_pagan.txt
copy Imperial.txt mazdaki.txt
copy Imperial.txt minoan.txt
